/**
 * Deterministic Linguistic Rule Engine
 *
 * Implements pure, algorithmic sentence transformations based on deep linguistic rules:
 * - Never generates text with unconstrained LLMs (which triggers AI detectors)
 * - Executes grammatical transformations: Voice, Clause Inversion, Nominalization,
 *   Litotes, Topicalization Fronting, Human Discourse Markers, and POS-locked Synonyms.
 * - Works identically whether the rule plan is generated by heuristic analyzer or by AI rule planner.
 */

import { ToneStyle, WordChange, TechniqueUsed, SentenceData } from '../types';
import {
  EXTENSIVE_LEXICON,
  DeepSynonymEntry,
  DEEP_NOMINALIZATIONS,
  EXTENSIVE_LITOTES_PAIRS,
  FRONTING_FRAMES,
  HUMAN_DISCOURSE_CONNECTORS,
  BANNED_AI_EXPRESSIONS,
  ACADEMIC_PHRASAL_TRANSFORMS,
} from './deepLinguisticDictionary';
import { tagSentence, POSTag } from './posTagger';
import {
  findProtectedSpans,
  isRangeProtected,
  lockStatisticalAndAcademicExpressions,
  INVARIANT_SCIENTIFIC_WORDS,
  BANNED_UNNATURAL_SYNONYMS,
} from './entityProtection';
import { isProtectedWord } from './paraphraserEngine';
import { isSectionHeading, analyzeSentenceForParaphrasing } from './sentenceValidator';
import { detectVoice, activeToPassive, passiveToActive } from './voiceTransformer';
import { reorderClauses } from './structureTransformer';
import { sanitizePunctuationSpacing } from './sanitizer';
import { restoreDomainTerms, sanitizeAiVocabulary, applyLinguisticHumanizationRules } from './humanizerAntiAi';

export interface SentenceRulePlan {
  sentenceIndex: number;
  isProperSentence: boolean;
  skipReason?: string;
  prefixToKeep?: string;
  plannedRules?: TechniqueUsed[];
  selectedRules?: string[];
  voiceDirective?: 'active' | 'passive' | 'keep';
  reorderClause?: boolean;
  nominalizeVerb?: string | null; // e.g. "analyze", "investigate"
  litotesShift?: boolean;
  frontingPhrase?: string | null;
  humanDiscourseMarker?: string | null;
  synonymSubstitutions?: Record<string, string>; // original -> replacement
  splitSentence?: boolean;
  combineWithNext?: boolean;
}

export interface RuleExecutionResult {
  paraphrasedText: string;
  techniques: TechniqueUsed[];
  wordChanges: WordChange[];
  rulesExplanation: string[];
  appliedVoice: 'active' | 'passive' | 'neutral';
  appliedStructure: 'simple' | 'compound' | 'complex';
}

let ruleEngineCounter = 0;
function getUniqueId(prefix: string): string {
  return `${prefix}-${Date.now()}-${++ruleEngineCounter}`;
}

function matchCase(original: string, replacement: string): string {
  if (!original || !replacement) return replacement;
  if (original === original.toUpperCase() && original.length > 1) {
    return replacement.toUpperCase();
  }
  if (original[0] === original[0].toUpperCase()) {
    return replacement.charAt(0).toUpperCase() + replacement.slice(1);
  }
  return replacement.toLowerCase();
}

/**
 * Strips robotic AI buzzwords & phrases and replaces them with authentic human phrasing.
 */
export function purgeAiClichés(text: string): { cleaned: string; replacedList: string[] } {
  let result = text;
  const replacedList: string[] = [];

  for (const [cliche, replacement] of Object.entries(BANNED_AI_EXPRESSIONS)) {
    const regex = new RegExp(`\\b${cliche.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'gi');
    if (regex.test(result)) {
      result = result.replace(regex, (match) => {
        replacedList.push(match);
        return matchCase(match, replacement);
      });
    }
  }

  return { cleaned: sanitizePunctuationSpacing(result), replacedList };
}

/**
 * Generates an optimal deterministic rule plan when AI is not used or offline.
 * Analyzes sentence syntax (voice, clauses, length, POS tags) to produce high human burstiness.
 */
export function generateDeterministicRulePlan(
  sentenceText: string,
  tone: ToneStyle,
  sentenceIndex: number,
  totalSentencesInPara: number,
  isHeadingContext: boolean = false,
  intensity: 'radical' | 'balanced' | 'conservative' = 'radical'
): SentenceRulePlan {
  const analysis = analyzeSentenceForParaphrasing(sentenceText, isHeadingContext);

  if (!analysis.shouldParaphrase) {
    return {
      sentenceIndex,
      isProperSentence: false,
      skipReason: analysis.reason,
      plannedRules: [],
    };
  }

  const coreText = analysis.coreSentenceToParaphrase;
  const words = coreText.split(/\s+/).filter(Boolean);
  const wordCount = words.length;

  const plannedRules: TechniqueUsed[] = [];
  const voice = detectVoice(coreText);

  // 1. Voice Directive: Convert passive to active (§11 Anti-AI Rule) or introduce variance
  let voiceDirective: 'active' | 'passive' | 'keep' = 'keep';
  if (voice.voice === 'passive') {
    voiceDirective = 'active';
    plannedRules.push('voice_active');
  } else if (intensity === 'radical' && voice.voice === 'active' && wordCount >= 10 && sentenceIndex % 3 === 2) {
    voiceDirective = 'passive';
    plannedRules.push('voice_passive');
  }

  // 2. Clause Reordering: Safe fronting or inversion of subordinate clauses
  // Breaks identical sentence length and word order footprints safely without corrupting syntax
  let reorderClause = false;
  if (!coreText.includes(':') && !coreText.includes(';')) {
    const hasSafeSubConj = /\b(because|although|even though|while|whereas|since|inasmuch as|given that|when|after|before|unless|as long as|provided that)\b/i.test(coreText);
    if (hasSafeSubConj && !/\bbecause\s+of\b/i.test(coreText)) {
      const minWordCount = intensity === 'radical' ? 6 : 8;
      reorderClause = wordCount >= minWordCount;
      if (reorderClause) {
        plannedRules.push('clause_reorder');
      }
    }
  }

  // 3. Nominalization: Word class shifts (Verbal predicate -> Scholarly nominal construct)
  let nominalizeVerb: string | undefined = undefined;
  const canNominalize = intensity === 'radical' ? wordCount >= 8 : (wordCount >= 12 && sentenceIndex % 2 === 0);
  if (canNominalize) {
    for (const [key, entry] of Object.entries(DEEP_NOMINALIZATIONS)) {
      const hasVerb = new RegExp(`\\b(?:${entry.pastVerb}|${entry.thirdVerb}|${entry.baseVerb})\\b`, 'i').test(coreText);
      const isPassive = new RegExp(`\\b(was|were|is|are|been|being|be)\\s+${entry.pastVerb}\\b`, 'i').test(coreText);
      if (hasVerb && !isPassive) {
        nominalizeVerb = key;
        plannedRules.push('word_class');
        break;
      }
    }
  }

  // 4. Litotes Shift (Affirmative -> Negative Litotes for scholarly variance)
  let litotesShift = false;
  if (tone === 'academic') {
    const hasLitotesTarget = EXTENSIVE_LITOTES_PAIRS.some((pair) =>
      new RegExp(`\\b${pair.affirmative}\\b`, 'i').test(coreText)
    );
    if (hasLitotesTarget && (intensity === 'radical' || sentenceIndex % 2 === 1)) {
      litotesShift = true;
      plannedRules.push('polarity_change');
    }
  }

  // 5. Human Discourse Marker: Never force artificial transitions
  const humanDiscourseMarker: string | undefined = undefined;

  // 6. Fronting Topicalization: Never force repetitive artificial frames
  const frontingPhrase: string | undefined = undefined;

  // 7. Context-Aware Synonyms
  plannedRules.push('synonym');

  return {
    sentenceIndex,
    isProperSentence: true,
    prefixToKeep: analysis.prefixToKeep,
    plannedRules,
    voiceDirective,
    reorderClause,
    nominalizeVerb,
    litotesShift,
    frontingPhrase,
    humanDiscourseMarker,
  };
}

/**
 * Adjusts candidate verb inflections (base, 3rd-person singular, or past tense)
 * to maintain strict grammatical subject-verb agreement with the original predicate.
 */
function inflectVerbCollocation(matchedText: string, replacementText: string): string {
  const matchWords = matchedText.trim().split(/\s+/);
  const repWords = replacementText.trim().split(/\s+/);
  if (matchWords.length === 0 || repWords.length === 0) return replacementText;

  const firstMatch = matchWords[0].toLowerCase();
  const firstRep = repWords[0];
  const firstRepLower = firstRep.toLowerCase();

  const isMatchPast = /(?:ed|d)$/.test(firstMatch) && !/^(?:and|need|lead)$/.test(firstMatch);
  const isMatch3rdSingular = /s$/.test(firstMatch) && !/ss$/.test(firstMatch);
  const isMatchBase = !isMatchPast && !isMatch3rdSingular;

  let newFirstRep = firstRep;

  if (isMatchBase) {
    if (firstRepLower === 'provides') newFirstRep = 'provide';
    else if (firstRepLower === 'illuminates') newFirstRep = 'illuminate';
    else if (firstRepLower === 'offers') newFirstRep = 'offer';
    else if (firstRepLower === 'underscores') newFirstRep = 'underscore';
    else if (firstRepLower === 'highlights') newFirstRep = 'highlight';
    else if (firstRepLower === 'serves') newFirstRep = 'serve';
    else if (firstRepLower === 'exerts') newFirstRep = 'exert';
    else if (firstRepLower === 'fosters') newFirstRep = 'foster';
    else if (firstRepLower === 'substantiates') newFirstRep = 'substantiate';
    else if (firstRepLower === 'demonstrates') newFirstRep = 'demonstrate';
    else if (firstRepLower === 'reveals') newFirstRep = 'reveal';
  } else if (isMatch3rdSingular) {
    if (firstRepLower === 'provide') newFirstRep = 'provides';
    else if (firstRepLower === 'illuminate') newFirstRep = 'illuminates';
    else if (firstRepLower === 'offer') newFirstRep = 'offers';
    else if (firstRepLower === 'underscore') newFirstRep = 'underscores';
    else if (firstRepLower === 'highlight') newFirstRep = 'highlights';
    else if (firstRepLower === 'serve') newFirstRep = 'serves';
    else if (firstRepLower === 'exert') newFirstRep = 'exerts';
    else if (firstRepLower === 'foster') newFirstRep = 'fosters';
    else if (firstRepLower === 'substantiate') newFirstRep = 'substantiates';
    else if (firstRepLower === 'demonstrate') newFirstRep = 'demonstrates';
    else if (firstRepLower === 'reveal') newFirstRep = 'reveals';
  } else if (isMatchPast) {
    if (firstRepLower === 'provide' || firstRepLower === 'provides') newFirstRep = 'provided';
    else if (firstRepLower === 'illuminate' || firstRepLower === 'illuminates') newFirstRep = 'illuminated';
    else if (firstRepLower === 'offer' || firstRepLower === 'offers') newFirstRep = 'offered';
    else if (firstRepLower === 'underscore' || firstRepLower === 'underscores') newFirstRep = 'underscored';
    else if (firstRepLower === 'highlight' || firstRepLower === 'highlights') newFirstRep = 'highlighted';
    else if (firstRepLower === 'serve' || firstRepLower === 'serves') newFirstRep = 'served';
    else if (firstRepLower === 'exert' || firstRepLower === 'exerts') newFirstRep = 'exerted';
  }

  repWords[0] = matchCase(firstRep, newFirstRep);
  return repWords.join(' ');
}

/**
 * Executes a SentenceRulePlan deterministically on a sentence.
 * Strictly guarantees that no LLM writes the text directly.
 */
export function executeLinguisticRulePlan(
  rawSentenceText: string,
  plan: SentenceRulePlan,
  tone: ToneStyle,
  preserveTechnicalTerms: boolean = true,
  intensity: 'radical' | 'balanced' | 'conservative' = 'radical'
): RuleExecutionResult {
  // If not a proper sentence (heading, fragment, table label), return untouched
  if (!plan.isProperSentence) {
    return {
      paraphrasedText: rawSentenceText,
      techniques: [],
      wordChanges: [],
      rulesExplanation: [`Preserved verbatim: ${plan.skipReason || 'Non-sentence segment'}`],
      appliedVoice: 'neutral',
      appliedStructure: 'simple',
    };
  }

  const techniques: TechniqueUsed[] = [];
  const wordChanges: WordChange[] = [];
  const rulesExplanation: string[] = [];

  // 1. Separate prefix before colon if present (e.g., "Note: ")
  let text = rawSentenceText;
  let prefix = '';
  if (plan.prefixToKeep) {
    prefix = plan.prefixToKeep;
    text = text.slice(prefix.length).trim();
  }

  // 2. Anti-AI Cliche Sanitization (e.g. replace "Furthermore", "delve into", "pivotal role")
  const { cleaned: unClicheText, replacedList } = purgeAiClichés(text);
  if (replacedList.length > 0) {
    text = unClicheText;
    rulesExplanation.push(`Purged robotic AI expressions: ${replacedList.join(', ')}`);
  }

  // 3. Multi-word Academic Phrasal Collocation Restructuring
  // Transposes multi-word academic patterns and scholarly idioms while strictly locking protected statistical terms
  const { lockedText: textForPhrasal, restore: restorePhrasalLocks } = lockStatisticalAndAcademicExpressions(text);
  let phrasalTransformed = textForPhrasal;

  for (const phr of ACADEMIC_PHRASAL_TRANSFORMS) {
    const phrRegex = new RegExp(phr.pattern.source, 'gi');
    if (phrRegex.test(phrasalTransformed)) {
      phrasalTransformed = phrasalTransformed.replace(phrRegex, (match) => {
        const candidates = phr[tone] || phr.academic;
        if (!candidates || candidates.length === 0) return match;
        const selected = candidates[(plan.sentenceIndex + match.length) % candidates.length];
        const inflected = inflectVerbCollocation(match, selected);
        const replaced = matchCase(match, inflected);
        techniques.push('phrase_shift');
        rulesExplanation.push(phr.explanation);
        wordChanges.push({
          id: getUniqueId('phr'),
          original: match,
          replaced,
          alternatives: [match, ...candidates],
          technique: 'phrase_shift',
          startIndex: 0,
          endIndex: 0,
          notes: phr.explanation,
        });
        return replaced;
      });
    }
  }
  text = restorePhrasalLocks(phrasalTransformed);

  // 4. Apply Voice Transformation (Active <-> Passive)
  let appliedVoice: 'active' | 'passive' | 'neutral' = detectVoice(text).voice;
  if (plan.voiceDirective === 'active' && appliedVoice === 'passive') {
    const vRes = passiveToActive(text);
    if (vRes.wasTransformed) {
      text = vRes.transformedText;
      appliedVoice = 'active';
      techniques.push('voice_active');
      rulesExplanation.push(vRes.explanation || 'Restructured passive construction to active voice');
    }
  } else if (plan.voiceDirective === 'passive' && appliedVoice === 'active') {
    const vRes = activeToPassive(text);
    if (vRes.wasTransformed) {
      text = vRes.transformedText;
      appliedVoice = 'passive';
      techniques.push('voice_passive');
      rulesExplanation.push(vRes.explanation || 'Restructured active construction to passive voice');
    }
  }

  // 5. Safe Clause Inversion / Fronting
  if (plan.reorderClause) {
    const reordered = reorderClauses(text);
    if (reordered.modified) {
      text = reordered.text;
      techniques.push('clause_reorder');
      rulesExplanation.push(reordered.ruleExplanation || 'Restructured subordinate clause for syntactic variation');
      if (reordered.wordChanges) {
        wordChanges.push(...reordered.wordChanges);
      }
    }
  }

  // 6. Apply Deep Nominalization / De-nominalization
  if (plan.nominalizeVerb && DEEP_NOMINALIZATIONS[plan.nominalizeVerb]) {
    const entry = DEEP_NOMINALIZATIONS[plan.nominalizeVerb];
    const phrases = tone === 'academic' ? entry.academicPhrases : entry.professionalPhrases;

    // Check past tense first: e.g. "analyzed" -> "conducted an empirical evaluation of"
    const pastRegex = new RegExp(`\\b${entry.pastVerb}\\b`, 'g');
    const passiveGuard = new RegExp(`\\b(was|were|is|are|been|being)\\s+${entry.pastVerb}\\b`, 'i');

    if (!passiveGuard.test(text) && pastRegex.test(text)) {
      text = text.replace(pastRegex, phrases.past);
      techniques.push('word_class');
      rulesExplanation.push(`Nominalized verbal predicate "${entry.pastVerb}" to scholarly phrase "${phrases.past}"`);
      wordChanges.push({
        id: getUniqueId('nom'),
        original: entry.pastVerb,
        replaced: phrases.past,
        alternatives: [entry.pastVerb, entry.baseVerb],
        technique: 'word_class',
        startIndex: 0,
        endIndex: 0,
        notes: `Nominalization of ${entry.baseVerb}`,
      });
    }
  }

  // 7. Apply Litotes / Polarity Inversion
  if (plan.litotesShift) {
    for (const pair of EXTENSIVE_LITOTES_PAIRS) {
      const affRegex = new RegExp(`\\b${pair.affirmative}\\b`, 'gi');
      if (affRegex.test(text)) {
        text = text.replace(affRegex, pair.negativeLitotes);
        techniques.push('polarity_change');
        rulesExplanation.push(`Applied scholarly litotes: shifted "${pair.affirmative}" to "${pair.negativeLitotes}"`);
        wordChanges.push({
          id: getUniqueId('litotes'),
          original: pair.affirmative,
          replaced: pair.negativeLitotes,
          alternatives: [pair.affirmative],
          technique: 'polarity_change',
          startIndex: 0,
          endIndex: 0,
          notes: 'Litotes polarity transformation',
        });
        break;
      }
    }
  }

  // 8. Context-Aware Lexical Substitution via EXTENSIVE_LEXICON
  // Lock all statistical notations, parentheticals, citations, and academic constructs
  const { lockedText: textToSub, restore: restoreLockedSub } = lockStatisticalAndAcademicExpressions(text);
  const protectedSpans = preserveTechnicalTerms ? findProtectedSpans(textToSub) : [];
  const taggedTokens = tagSentence(textToSub);
  const transformedTokens: string[] = [];
  let charOffset = 0;
  let wordIdx = 0;
  let substitutionsCount = 0;

  // Dynamic substitution density: In radical mode, allow substantial transformation (up to 70% of tokens)
  const substitutionRatio = intensity === 'radical' ? 0.70 : intensity === 'balanced' ? 0.45 : 0.20;
  const minSubs = intensity === 'radical' ? 5 : intensity === 'balanced' ? 3 : 1;
  const maxAllowedSubstitutions = Math.max(minSubs, Math.floor(taggedTokens.length * substitutionRatio));

  for (let i = 0; i < taggedTokens.length; i++) {
    const item = taggedTokens[i];
    const tok = item.token;
    const cleanWord = item.cleanWord;
    const tag = item.tag;

    const tokStart = textToSub.indexOf(tok, charOffset);
    const tokEnd = tokStart !== -1 ? tokStart + tok.length : charOffset + tok.length;
    if (tokStart !== -1) {
      if (tokStart > charOffset) {
        transformedTokens.push(textToSub.slice(charOffset, tokStart));
      }
      charOffset = tokEnd;
    }

    if (!tok || /^\s+$/.test(tok) || tag === 'PUNCT') {
      transformedTokens.push(tok);
      continue;
    }

    // Never modify locked tokens
    if (tok.startsWith('__PROT_LOCK_')) {
      transformedTokens.push(tok);
      continue;
    }

    const isSentenceStart = wordIdx === 0;
    wordIdx++;

    // Guard: Invariant scientific and research vocabulary
    if (INVARIANT_SCIENTIFIC_WORDS.has(cleanWord.toLowerCase())) {
      transformedTokens.push(tok);
      continue;
    }

    // Guard: Technical terms, citations, p-values, formulas
    if (preserveTechnicalTerms && isRangeProtected(tokStart, tokEnd, protectedSpans)) {
      transformedTokens.push(tok);
      continue;
    }
    if (preserveTechnicalTerms && isProtectedWord(tok, isSentenceStart)) {
      transformedTokens.push(tok);
      continue;
    }

    // Check plan-provided substitutions first (if AI rule planner specified preference and budget allows)
    if (plan.synonymSubstitutions && plan.synonymSubstitutions[cleanWord] && substitutionsCount < maxAllowedSubstitutions) {
      const suggested = plan.synonymSubstitutions[cleanWord].toLowerCase();
      // Filter out low-quality/slop synonyms, AI cliches, and inappropriate academic terms
      const isBanned =
        BANNED_UNNATURAL_SYNONYMS.has(suggested) ||
        suggested.includes('deleterious') ||
        suggested === 'ordered review' ||
        suggested.includes('scrutiny') ||
        suggested.includes('documentation') ||
        suggested.includes('appraisal') ||
        suggested.includes('empirical observation') ||
        (cleanWord === 'use' && suggested === 'employ');

      if (!isBanned) {
        const rep = matchCase(tok, plan.synonymSubstitutions[cleanWord]);
        transformedTokens.push(rep);
        techniques.push('synonym');
        substitutionsCount++;
        wordChanges.push({
          id: getUniqueId('syn-plan'),
          original: tok,
          replaced: rep,
          alternatives: [tok],
          technique: 'synonym',
          startIndex: tokStart,
          endIndex: tokEnd,
          notes: `Rule-planned synonym`,
        });
        continue;
      }
    }

    // Context-Aware Dictionary Lookup with POS Enforcement
    let entry: DeepSynonymEntry | undefined = undefined;

    // Special case: "use" (noun vs verb)
    if (cleanWord === 'use') {
      entry = tag === 'NOUN' ? EXTENSIVE_LEXICON['use_noun'] : EXTENSIVE_LEXICON['use_verb'];
    } else {
      const candidate = EXTENSIVE_LEXICON[cleanWord];
      if (candidate) {
        // Enforce POS compatibility
        const isNounCompatible = tag === 'NOUN' && (candidate.pos === 'noun' || candidate.pos === 'adj');
        const isVerbCompatible = tag === 'VERB' && candidate.pos === 'verb';
        const isAdjCompatible = tag === 'ADJ' && candidate.pos === 'adj';
        const isAdvCompatible = tag === 'ADV' && candidate.pos === 'adv';

        if (isNounCompatible || isVerbCompatible || isAdjCompatible || isAdvCompatible) {
          entry = candidate;
        }
      }
    }

    if (entry && substitutionsCount < maxAllowedSubstitutions) {
      const candidates = entry[tone] || entry.professional;
      if (candidates && candidates.length > 0) {
        // Filter out banned words, cliches, and awkward synonyms
        const filtered = candidates.filter((c) => {
          const lower = c.toLowerCase();
          return (
            !BANNED_UNNATURAL_SYNONYMS.has(lower) &&
            !lower.includes('deleterious') &&
            !lower.includes('scrutiny') &&
            !lower.includes('documentation') &&
            !lower.includes('appraisal') &&
            !lower.includes('empirical observation') &&
            c !== 'ordered'
          );
        });
        if (filtered.length > 0) {
          const selected = filtered[charOffset % filtered.length];
          const replacedWord = matchCase(tok, selected);

          transformedTokens.push(replacedWord);
          techniques.push('synonym');
          substitutionsCount++;
          wordChanges.push({
            id: getUniqueId('syn'),
            original: tok,
            replaced: replacedWord,
            alternatives: [tok, ...filtered],
            technique: 'synonym',
            startIndex: tokStart,
            endIndex: tokEnd,
            notes: `POS-locked (${tag}) synonym in ${tone} register`,
          });
          continue;
        }
      }
    }

    transformedTokens.push(tok);
  }

  if (charOffset < textToSub.length) {
    transformedTokens.push(textToSub.slice(charOffset));
  }

  // Restore all locked statistical notations, citations, and fixed constructs
  text = restoreLockedSub(transformedTokens.join(''));

  // 8. Human Discourse Connector Injection (Only if non-redundant and not stacked)
  if (plan.humanDiscourseMarker) {
    const markerClean = plan.humanDiscourseMarker.trim();
    // Guard against stacked transitions (e.g., "Beyond this, at the same time")
    const existingTransitionRegex = /^(?:beyond this|at the same time|specifically|equally important|moreover|furthermore|additionally|however|nevertheless|in contrast|conversely|in addition),?\s*/i;
    if (!existingTransitionRegex.test(text) && !text.toLowerCase().startsWith(markerClean.toLowerCase())) {
      // Guard: Never lowercase proper names or author citations (e.g., "Festinger's (1954)")
      const firstWord = text.split(/\s+/)[0] || '';
      const isProperNounOrCitation = /^[A-Z][a-z]+(?:'s)?$/.test(firstWord) && !/^(The|A|An|This|These|That|Those|In|On|At|For|With|By|From|To|As)$/.test(firstWord);
      const lowercasedStart = (text.startsWith('I ') || isProperNounOrCitation) ? text : text.charAt(0).toLowerCase() + text.slice(1);
      text = `${markerClean} ${lowercasedStart}`;
      rulesExplanation.push(`Introduced natural human transition: "${markerClean}"`);
    }
  }

  // 9. Fronting / Topicalization (Prepositional Frame)
  if (plan.frontingPhrase && !plan.humanDiscourseMarker) {
    const frameClean = plan.frontingPhrase.trim();
    const existingFrameRegex = /^(?:within this|in this|across the|from an operational|under this|based on),?\s*/i;
    if (!existingFrameRegex.test(text) && !text.toLowerCase().startsWith(frameClean.toLowerCase())) {
      const firstWord = text.split(/\s+/)[0] || '';
      const isProperNounOrCitation = /^[A-Z][a-z]+(?:'s)?$/.test(firstWord) && !/^(The|A|An|This|These|That|Those|In|On|At|For|With|By|From|To|As)$/.test(firstWord);
      const lowercasedStart = (text.startsWith('I ') || isProperNounOrCitation) ? text : text.charAt(0).toLowerCase() + text.slice(1);
      text = `${frameClean} ${lowercasedStart}`;
      rulesExplanation.push(`Fronted topical frame: "${frameClean}"`);
    }
  }

  // 10. Restore Domain Invariants (sample, dataset, correlated, university students)
  text = restoreDomainTerms(rawSentenceText, text);

  // 10b. Apply 25-Rule Anti-AI Humanizer (strips AI clichés, corrects Not X but Y, balances syntax)
  const humanized = applyLinguisticHumanizationRules(text, tone);
  if (humanized.appliedRulesCount > 0) {
    text = humanized.transformedText;
    rulesExplanation.push(...humanized.rulesApplied);
  }
  text = restoreDomainTerms(rawSentenceText, text);

  // 11. Re-attach prefix before colon if present
  if (prefix) {
    text = `${prefix} ${text}`;
  }

  // 12. Final spacing and punctuation cleanup
  text = sanitizePunctuationSpacing(text);

  // Structure detection
  const appliedStructure: 'simple' | 'compound' | 'complex' = text.includes(';') || /,\s*(and|but|yet|so)\b/i.test(text)
    ? 'compound'
    : /^(although|because|while|since|if)\b/i.test(text) || text.includes(',')
    ? 'complex'
    : 'simple';

  return {
    paraphrasedText: text,
    techniques: Array.from(new Set(techniques)),
    wordChanges,
    rulesExplanation: rulesExplanation.length > 0 ? rulesExplanation : ['Applied deep linguistic syntax rules.'],
    appliedVoice,
    appliedStructure,
  };
}
